spool 9056_views.log
set timing on time on echo on

create synonym ACCOUNTSUGGESTEDPRODUCT_ACTIVE for s4.ACCOUNTSUGGESTEDPRODUCT_ACTIVE ;
create synonym ACCOUNTSUGGESTEDPRODUCT_CTA for s4.ACCOUNTSUGGESTEDPRODUCT_CTA;
create synonym ACCOUNTSUGGESTEDPRODUCT_TEMP for s4.ACCOUNTSUGGESTEDPRODUCT_TEMP;
create synonym ACCT_XREF_COMBINED for s4.ACCT_XREF_COMBINED;
create synonym ASP_SUPPRESS_VIEW for s4.ASP_SUPPRESS_VIEW;
create synonym ASP_TEST_VW for s4.ASP_TEST_VW;
create synonym JARICH_VW1 for s4.JARICH_VW1;
create synonym PRODUCTOFFERSERVICESDETAIL for s4.PRODUCTOFFERSERVICESDETAIL;
create synonym SOURCECODE for s4.SOURCECODE;


spool off
exit
